version: '3'
services:
  redis:
    image: redis:latest
    container_name: chatwoot-adapter-redis
    #restart: unless-stopped
    hostname: redis
    network_mode: bridge
    ports:
      - 127.0.0.1:${REDIS_PORT}:6379/tcp
    volumes:
       - chatwoot-adapter-redis-data:/data
    command: ["redis-server", "--requirepass ${REDIS_PASSWORD}"]


networks:
  chatwoot-adapter-backend:
    driver: bridge

volumes:
  chatwoot-adapter-redis-data: